# Docker Compose File for Application Container with Docker bindings
version: '3.8'

services:
  dev:
    image: mcr.microsoft.com/devcontainers/javascript-node:dev-20-bookworm
    command: sleep infinity

    ports:
      - "3000:3000"
      - "5137:5137"

    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
